name: behaves as lambda

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  execution:
    name: execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Install dependencies
        run: npm ci
      - name: Execute run
        env:
          CYPRESS_MESSAGE: ${{ github.event.client_payload.message }}
        run: npx cypress run
      - uses: actions/upload-artifact@v4
        name: Upload artifacts
        with:
          name: videos
          path: cypress/videos
