name: behaves as lambda

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  e2e-tests:
    name: execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - name: Install dependencies
        run: npm ci
      - name: Execute run
        run: npx cypress run
      - uses: actions/upload-artifact@v4
        name: Upload artifacts
        with:
          name: videos
          path: cypress/videos
